/** User-facing copy for the dsh-ios simulator cards (en/zh, like the host). */

export type SimLocale = 'en' | 'zh'

const COPY = {
  en: {
    simulator: 'iOS Simulator',
    actionBoot: 'Boot',
    actionScreenshot: 'Screenshot',
    actionInteract: 'Interact',
    actionBuildRun: 'Build & Run',
    booting: 'Booting the simulator…',
    connecting: 'Connecting to the live stream…',
    connectingScreenshot: 'Loading screenshot…',
    live: 'live',
    unavailable: 'unavailable',
    done: 'done',
    streamUnavailable: 'stream not available',
    screenshotUnavailable: 'screenshot not available',
    retry: 'Retry',
    refresh: 'Refresh',
    home: 'Home',
    homeHint: 'Home · double-click for the app switcher',
    deviceMenu: 'Device actions',
    deviceAppSwitcher: 'App Switcher',
    deviceLock: 'Lock',
    deviceUnlock: 'Unlock',
    deviceShake: 'Shake',
    deviceSiri: 'Siri',
    deviceActionButton: 'Action Button',
    deviceReCenter: 'Re-center window',
    deviceActionUnsupported: 'not available on a physical device',
    deviceActionFailed: 'the device action failed',
    screenshot: 'Screenshot',
    captured: 'Captured',
    capturing: 'Capturing…',
    rotate: 'Rotate',
    toolbar: 'Simulator toolbar',
    sizeMode: 'Simulator display size',
    frameStyle: 'Simulator frame style',
    frameStyleNone: 'Frameless',
    frameStyleBezel: 'Bezel',
    frameStyleDevice: 'Device frame',
    sizeQuickFit: 'Fit to panel width',
    sizeQuickPercent100: 'Display at 100%',
    sizeQuickS: 'Small size (S, 240px)',
    sizeQuickM: 'Medium size (M, 320px)',
    streamAlt: 'Live iOS Simulator — click to tap, drag to gesture',
    screenshotAlt: 'iOS Simulator screenshot',
    captureScreenshot: 'Capturing screenshot…',
    interacting: 'Interacting with the simulator…',
    building: 'Building and launching the app…',
    noPreview: 'No live view is available for this result.',
    toolFailed: 'The tool call failed.',
    openApp: 'Open app bundle',
    openScreenshot: 'Open screenshot',
    bundleId: 'Bundle ID',
    device: 'device',
    offline: 'Offline',
    panelLive: 'Live',
    closePanel: 'Close simulator panel',
    resizePanel: 'Drag to resize the simulator panel',
    openInPanel: 'Open in sidebar',
    openSimulatorPanel: 'Open simulator panel',
    devicePicker: 'Simulator device',
    deviceSwitching: 'Switching…',
    deviceBooted: 'booted',
    deviceStreaming: 'live',
    realDevices: 'Physical devices',
    realDevicesNone: 'No device connected',
    realDeviceConnected: 'connected',
    realDeviceUnavailable: 'unavailable',
    realDeviceMode: 'Physical device',
    realDeviceNoStream: 'The live view needs WebDriverAgent running on the phone — start it (or unlock/trust/plug in), then tap Retry to re-check.',
    realDeviceUdid: 'Device ID',
    realDeviceHint: 'Ask the agent to target this device by its ID.',
    realDeviceChecking: 'Checking WebDriverAgent…',
    realDeviceConnecting: 'Connecting to the phone…',
    realDeviceNotRunning: 'WebDriverAgent is not running on the phone — tap Start WebDriverAgent (a first build can take minutes), or run ios_real_start_wda.',
    realDeviceLocked: 'The phone is locked — unlock it and tap Retry. WDA recovers by itself once the phone is unlocked.',
    realDeviceCertUntrusted: 'The Developer App certificate is not trusted — trust it once in Settings → General → VPN & Device Management on the phone, then tap Start WebDriverAgent.',
    realDeviceProfileExpired: 'The free-team provisioning profile expired (7-day lifetime) — tap Start WebDriverAgent to rebuild, then Retry to re-check.',
    realDeviceUnplugged: 'The phone is not connected over USB — plug it in and tap Retry.',
    realDeviceBuildFailed: 'The WebDriverAgentRunner build failed — fix the build error and tap Start WebDriverAgent.',
    realDeviceLaunchTimeout: 'WebDriverAgent took too long to come up — a cold build can take minutes; tap Start WebDriverAgent to try again.',
    realDeviceTunnelFailed: 'The USB tunnel to the phone failed — check the cable/connection and tap Retry.',
    realDeviceWdaNotReady: 'WebDriverAgent answered but is not ready — tap Retry to check again.',
    realDeviceWdaUnavailable: 'WebDriverAgent tooling is unavailable on this host (Xcode + iproxy + the WDA checkout are required).',
    realDeviceRetryHint: 'After fixing the issue, tap Start WebDriverAgent to build/launch, or Retry to only re-check the phone.',
    realStartAction: 'Start WebDriverAgent',
    realStartProgress: 'Starting WebDriverAgent — the first build can take minutes; the live view appears automatically once it is ready.',
    realStartLockedHint: 'The phone is locked — unlock it; WDA keeps waiting and recovers by itself.',
    realStartTimeout: 'WebDriverAgent did not become ready within 8 minutes — check the phone (unlocked, certificate trusted, plugged in over USB) and tap Start again.',
    backToSimulator: 'Back to the simulator',
    // Auto-follow indicator (the panel follows the agent's newest target).
    followActive: 'Auto-follow',
    followHint: 'The panel follows the agent\u2019s newest target device',
    followResume: 'Resume following',
    errForbidden: 'the request was refused (loopback-trusted browsers only)',
    errBadMethod: 'the route refused this request method',
    errBadContentType: 'the route expects a JSON request',
    errBadRequest: 'the request was malformed',
    errDeviceUnknown: 'the simulator does not exist or is unavailable',
    errDeviceNotBooted: 'the simulator is not booted',
    errDeviceBusy: 'another simulator is streaming; pick it in the device list to switch',
    errStreamNotRunning: 'no stream is running for this device',
    errStreamFailed: 'the simulator stream failed to start',
    errTokenInvalid: 'the access link expired; refresh to get a new one',
    errScreenshotMissing: 'the screenshot file is gone',
    errUnavailable: 'the simulator is unavailable',
    errWdaNotRunning: 'WebDriverAgent is not running on the phone',
    errWdaDeviceLocked: 'the phone is locked — unlock it and retry',
    errWdaCertUntrusted: 'the Developer App certificate is not trusted on the phone',
    errWdaProfileExpired: 'the provisioning profile expired — re-run the WDA build',
    errWdaDeviceUnplugged: 'the phone is not connected over USB',
    errWdaBuildFailed: 'the WebDriverAgentRunner build failed',
    errWdaLaunchTimeout: 'WebDriverAgent did not come up in time',
    errWdaTunnelFailed: 'the USB tunnel to the phone failed',
    errWdaNotReady: 'WebDriverAgent is not ready yet',
    errWdaUnavailable: 'WebDriverAgent tooling is unavailable on this host',
    switchFailed: 'Switch failed',
  },
  zh: {
    simulator: 'iOS 模拟器',
    actionBoot: '启动',
    actionScreenshot: '截图',
    actionInteract: '交互',
    actionBuildRun: '构建运行',
    booting: '正在启动模拟器…',
    connecting: '正在连接实时画面…',
    connectingScreenshot: '正在加载截图…',
    live: '实时',
    unavailable: '不可用',
    done: '完成',
    streamUnavailable: '画面不可用',
    screenshotUnavailable: '截图不可用',
    retry: '重试',
    refresh: '刷新',
    home: '回到桌面',
    homeHint: '回到桌面 · 双击打开后台 App',
    deviceMenu: '设备操作',
    deviceAppSwitcher: '后台 App',
    deviceLock: '锁屏',
    deviceUnlock: '解锁',
    deviceShake: '摇一摇',
    deviceSiri: 'Siri',
    deviceActionButton: 'Action 按钮',
    deviceReCenter: '窗口重新居中',
    deviceActionUnsupported: '真机不支持该操作',
    deviceActionFailed: '设备操作失败',
    screenshot: '截图',
    captured: '已截图',
    capturing: '正在截图…',
    rotate: '旋转',
    toolbar: '模拟器工具栏',
    frameStyle: '模拟器边框样式',
    frameStyleNone: '无框',
    frameStyleBezel: '边框',
    frameStyleDevice: '真机框',
    sizeQuickFit: '适应面板宽度',
    sizeQuickPercent100: '以 100% 显示',
    sizeQuickS: '小尺寸（S，240px）',
    sizeQuickM: '中尺寸（M，320px）',
    streamAlt: '实时 iOS 模拟器 — 点击轻触，拖动手势',
    screenshotAlt: 'iOS 模拟器截图',
    captureScreenshot: '正在截取屏幕…',
    interacting: '正在与模拟器交互…',
    building: '正在构建并启动应用…',
    noPreview: '此结果没有可用的实时视图。',
    toolFailed: '工具调用失败。',
    openApp: '打开应用包',
    openScreenshot: '打开截图',
    bundleId: 'Bundle ID',
    device: '设备',
    offline: '离线',
    panelLive: '实时',
    closePanel: '关闭模拟器面板',
    resizePanel: '拖动调整模拟器面板宽度',
    openInPanel: '在侧边栏打开',
    openSimulatorPanel: '打开模拟器面板',
    sizeMode: '模拟器显示大小',
    devicePicker: '模拟器设备',
    deviceSwitching: '切换中…',
    deviceBooted: '已启动',
    deviceStreaming: '实时',
    realDevices: '真机',
    realDevicesNone: '未连接设备',
    realDeviceConnected: '已连接',
    realDeviceUnavailable: '不可用',
    realDeviceMode: '真机',
    realDeviceNoStream: '实时画面需要手机上的 WebDriverAgent 正在运行——先启动它（或解锁、信任、插上数据线），然后点击重试重新检查。',
    realDeviceUdid: '设备 ID',
    realDeviceHint: '让 agent 用这个 ID 指定目标设备。',
    realDeviceChecking: '正在检查 WebDriverAgent…',
    realDeviceConnecting: '正在连接真机画面…',
    realDeviceNotRunning: '手机上的 WebDriverAgent 未运行——点击“启动 WebDriverAgent”（首次构建可能需要几分钟），或让 agent 运行 ios_real_start_wda。',
    realDeviceLocked: '手机已锁定——解锁后点击重试；解锁后 WDA 会自动恢复。',
    realDeviceCertUntrusted: '开发者应用证书未受信任——在手机上前往 设置 → 通用 → VPN 与设备管理 信任一次，然后点击“启动 WebDriverAgent”。',
    realDeviceProfileExpired: '免费开发者描述文件已过期（有效期 7 天）——点击“启动 WebDriverAgent”重新构建，然后重试。',
    realDeviceUnplugged: '手机未通过 USB 连接——插上数据线后点击重试。',
    realDeviceBuildFailed: 'WebDriverAgentRunner 构建失败——修复构建错误后点击“启动 WebDriverAgent”。',
    realDeviceLaunchTimeout: 'WebDriverAgent 启动超时——冷构建可能需要几分钟；点击“启动 WebDriverAgent”重试。',
    realDeviceTunnelFailed: '到手机的 USB 转发失败——检查线缆连接后点击重试。',
    realDeviceWdaNotReady: 'WebDriverAgent 已响应但尚未就绪——点击重试再次检查。',
    realDeviceWdaUnavailable: '此主机缺少 WebDriverAgent 工具链（需要 Xcode + iproxy + WDA 源码目录）。',
    realDeviceRetryHint: '解决问题后，点击“启动 WebDriverAgent”重新构建启动，或点击重试仅重新检查。',
    realStartAction: '启动 WebDriverAgent',
    realStartProgress: '正在启动 WebDriverAgent——首次构建可能需要几分钟；就绪后会自动出现实时画面。',
    realStartLockedHint: '手机已锁定——请解锁；WDA 会继续等待并自动恢复。',
    realStartTimeout: 'WebDriverAgent 在 8 分钟内未就绪——请检查手机（已解锁、证书已信任、已连接数据线），然后重新点击“启动 WebDriverAgent”。',
    backToSimulator: '返回模拟器',
    // Auto-follow indicator (the panel follows the agent's newest target).
    followActive: '自动跟随',
    followHint: '面板自动跟随 agent 的最新目标设备',
    followResume: '恢复跟随',
    errForbidden: '请求被拒绝（仅限本机可信浏览器）',
    errBadMethod: '该路由不接受此请求方法',
    errBadContentType: '该路由需要 JSON 请求',
    errBadRequest: '请求格式不正确',
    errDeviceUnknown: '该模拟器不存在或不可用',
    errDeviceNotBooted: '该模拟器尚未启动',
    errDeviceBusy: '另一台模拟器正在推流；在设备列表里选择它即可切换',
    errStreamNotRunning: '该设备没有正在运行的画面流',
    errStreamFailed: '模拟器画面流启动失败',
    errTokenInvalid: '访问链接已过期，刷新即可重新获取',
    errScreenshotMissing: '截图文件已不存在',
    errUnavailable: '模拟器不可用',
    errWdaNotRunning: '手机上的 WebDriverAgent 未运行',
    errWdaDeviceLocked: '手机已锁定——解锁后重试',
    errWdaCertUntrusted: '手机上的开发者应用证书未受信任',
    errWdaProfileExpired: '描述文件已过期——重新构建 WDA',
    errWdaDeviceUnplugged: '手机未通过 USB 连接',
    errWdaBuildFailed: 'WebDriverAgentRunner 构建失败',
    errWdaLaunchTimeout: 'WebDriverAgent 未在限定时间内启动',
    errWdaTunnelFailed: '到手机的 USB 转发失败',
    errWdaNotReady: 'WebDriverAgent 尚未就绪',
    errWdaUnavailable: '此主机缺少 WebDriverAgent 工具链',
    switchFailed: '切换失败',
  },
} as const

export type SimCopy = { readonly [Key in keyof typeof COPY.en]: string }

export function simCopy(locale: string | undefined): SimCopy {
  return locale === 'zh' ? COPY.zh : COPY.en
}

/** Human-readable byte size for the screenshot caption. */
export function formatBytes(bytes: number | undefined): string | undefined {
  if (typeof bytes !== 'number' || !Number.isFinite(bytes) || bytes < 0) return undefined
  if (bytes < 1024) return `${bytes} B`
  return `${(bytes / 1024).toFixed(1)} KB`
}
