/** User-facing copy for the dsh-ios simulator cards (en/zh, like the host). */

export type SimLocale = 'en' | 'zh'

const COPY = {
  en: {
    simulator: 'iOS Simulator',
    actionBoot: 'Boot',
    actionScreenshot: 'Screenshot',
    actionInteract: 'Interact',
    actionBuildRun: 'Build & Run',
    booting: 'Booting the simulator…',
    connecting: 'Connecting to the live stream…',
    connectingScreenshot: 'Loading screenshot…',
    live: 'live',
    unavailable: 'unavailable',
    done: 'done',
    streamUnavailable: 'stream not available',
    screenshotUnavailable: 'screenshot not available',
    retry: 'Retry',
    refresh: 'Refresh',
    home: 'Home',
    screenshot: 'Screenshot',
    captured: 'Captured',
    capturing: 'Capturing…',
    rotate: 'Rotate',
    toolbar: 'Simulator toolbar',
    sizeMode: 'Simulator display size',
    frameStyle: 'Simulator frame style',
    frameStyleNone: 'Frameless',
    frameStyleBezel: 'Bezel',
    frameStyleDevice: 'Device frame',
    sizeQuickFit: 'Fit to panel width',
    sizeQuickPercent100: 'Display at 100%',
    sizeQuickS: 'Small size (S, 240px)',
    sizeQuickM: 'Medium size (M, 320px)',
    streamAlt: 'Live iOS Simulator — click to tap, drag to gesture',
    screenshotAlt: 'iOS Simulator screenshot',
    captureScreenshot: 'Capturing screenshot…',
    interacting: 'Interacting with the simulator…',
    building: 'Building and launching the app…',
    noPreview: 'No live view is available for this result.',
    toolFailed: 'The tool call failed.',
    openApp: 'Open app bundle',
    openScreenshot: 'Open screenshot',
    bundleId: 'Bundle ID',
    device: 'device',
    offline: 'Offline',
    panelLive: 'Live',
    closePanel: 'Close simulator panel',
    resizePanel: 'Drag to resize the simulator panel',
    openInPanel: 'Open in sidebar',
    openSimulatorPanel: 'Open simulator panel',
  },
  zh: {
    simulator: 'iOS 模拟器',
    actionBoot: '启动',
    actionScreenshot: '截图',
    actionInteract: '交互',
    actionBuildRun: '构建运行',
    booting: '正在启动模拟器…',
    connecting: '正在连接实时画面…',
    connectingScreenshot: '正在加载截图…',
    live: '实时',
    unavailable: '不可用',
    done: '完成',
    streamUnavailable: '画面不可用',
    screenshotUnavailable: '截图不可用',
    retry: '重试',
    refresh: '刷新',
    home: '回到桌面',
    screenshot: '截图',
    captured: '已截图',
    capturing: '正在截图…',
    rotate: '旋转',
    toolbar: '模拟器工具栏',
    frameStyle: '模拟器边框样式',
    frameStyleNone: '无框',
    frameStyleBezel: '边框',
    frameStyleDevice: '真机框',
    sizeQuickFit: '适应面板宽度',
    sizeQuickPercent100: '以 100% 显示',
    sizeQuickS: '小尺寸（S，240px）',
    sizeQuickM: '中尺寸（M，320px）',
    streamAlt: '实时 iOS 模拟器 — 点击轻触，拖动手势',
    screenshotAlt: 'iOS 模拟器截图',
    captureScreenshot: '正在截取屏幕…',
    interacting: '正在与模拟器交互…',
    building: '正在构建并启动应用…',
    noPreview: '此结果没有可用的实时视图。',
    toolFailed: '工具调用失败。',
    openApp: '打开应用包',
    openScreenshot: '打开截图',
    bundleId: 'Bundle ID',
    device: '设备',
    offline: '离线',
    panelLive: '实时',
    closePanel: '关闭模拟器面板',
    resizePanel: '拖动调整模拟器面板宽度',
    openInPanel: '在侧边栏打开',
    openSimulatorPanel: '打开模拟器面板',
    sizeMode: '模拟器显示大小',
  },
} as const

export type SimCopy = { readonly [Key in keyof typeof COPY.en]: string }

export function simCopy(locale: string | undefined): SimCopy {
  return locale === 'zh' ? COPY.zh : COPY.en
}

/** Human-readable byte size for the screenshot caption. */
export function formatBytes(bytes: number | undefined): string | undefined {
  if (typeof bytes !== 'number' || !Number.isFinite(bytes) || bytes < 0) return undefined
  if (bytes < 1024) return `${bytes} B`
  return `${(bytes / 1024).toFixed(1)} KB`
}
